force-app/main/default/objects/Git_Hosting_Service__mdt/Git_Hosting_Service__mdt.object-meta.xml
<CustomObject>
    <label>Git Hosting Service</label>
    <pluralLabel>Git Hosting Services</pluralLabel>
</CustomObject>

force-app/core/default/objects/Git_Hosting_Service__mdt/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <inlineHelpText>Must extend from GitHostingService</inlineHelpText>
    <label>Apex Class</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/core/default/objects/Git_Hosting_Service__mdt/fields/Get_File_Tree_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Get_File_Tree_Endpoint__c</fullName>
    <label>Get File Tree Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Git_Hosting_Service__mdt/fields/Get_Repos_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Get_Repos_Endpoint__c</fullName>
    <label>Get Repos Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Git_Hosting_Service__mdt/fields/Get_Team_Repos_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Get_Team_Repos_Endpoint__c</fullName>
    <label>Get Team Repos Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Git_Hosting_Service__mdt/fields/Named_Credential_Name__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential_Name__c</fullName>
    <label>Named Credential Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Git_Hosting_Service__mdt/fields/Page_Parameter__c.field-meta.xml
<CustomField>
    <fullName>Page_Parameter__c</fullName>
    <label>Page Parameter</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/core/default/objects/Git_Hosting_Service__mdt/fields/Page_Size_Parameter__c.field-meta.xml
<CustomField>
    <fullName>Page_Size_Parameter__c</fullName>
    <label>Page Size Parameter</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GitHostingConfig.cls
global with sharing class GitHostingConfig extends VisualEditor.DynamicPickList {
    
    private static Map<String, Git_Hosting_Service__mdt> cachedConfig = new Map<String, Git_Hosting_Service__mdt>();

    /**
     * ***********************************
     * INHERTIED IMPLEMENTATION
     * ***********************************
     */

    global override VisualEditor.DataRow getDefaultValue(){
        
        Git_Hosting_Service__mdt config = GitHostingConfig.getGitHosts().values()[0];

        return new VisualEditor.DataRow(config.MasterLabel, config.MasterLabel);
    }

    global override VisualEditor.DynamicPickListRows getValues() {

        VisualEditor.DynamicPickListRows configuredHosts = new VisualEditor.DynamicPickListRows();

        for (String gitHostName : GitHostingConfig.getGitHosts().keySet()) {
            configuredHosts.addRow(new VisualEditor.DataRow(gitHostName, gitHostName));
        }

        return configuredHosts;
    }

    /**
     * ***********************************
     * STATIC IMPLEMENTATION
     * ***********************************
     */

    /**
     * Obtain the configured git hostings
     */
    global static Map<String, Git_Hosting_Service__mdt> getGitHosts() {

        if (GitHostingConfig.cachedConfig.isEmpty()) {
            
            for (Git_Hosting_Service__mdt config : [SELECT MasterLabel, Apex_Class__c, Get_Repos_Endpoint__c, Get_Team_Repos_Endpoint__c,
                                                    Get_File_Tree_Endpoint__c, 
                                                    Named_Credential_Name__c, Page_Parameter__c, Page_Size_Parameter__c 
                                                    FROM Git_Hosting_Service__mdt]) {
                
                GitHostingConfig.cachedConfig.put(config.MasterLabel, config);
            }
        }

        return GitHostingConfig.cachedConfig;
    }


    /**
     * Obtain git hosting config for a specific service
     * @param  hostingService - git hosting service name
     */
    global static Git_Hosting_Service__mdt getSpecificGitHost(String hostingService) {
        return GitHostingConfig.getGitHosts().get(hostingService);
    }


    /**
     * Obtain the hosting service apex instance
     * @param  hostingService - git hosting service name
     */
    global static GitHostingService getServiceInstance(String hostingService) {
        
        Git_Hosting_Service__mdt hostingConfig = GitHostingConfig.getSpecificGitHost(hostingService);

        if (hostingConfig == null) {
            throw new InvalidServiceException('Hosting service not configured: ' + hostingService);
        }

        Type t = Type.forName(hostingConfig.Apex_Class__c);
        return (GitHostingService)t.newInstance();
    }


    public class InvalidServiceException extends Exception {}
}