force-app/main/default/objects/Git_Hosting_Service__mdt/Git_Hosting_Service__mdt.object-meta.xml
<CustomObject>
    <label>Git Hosting Service</label>
    <pluralLabel>Git Hosting Services</pluralLabel>
</CustomObject>

force-app/core/default/objects/Git_Hosting_Service__mdt/fields/Get_File_Tree_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Get_File_Tree_Endpoint__c</fullName>
    <label>Get File Tree Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Git_Hosting_Service__mdt/fields/Named_Credential_Name__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential_Name__c</fullName>
    <label>Named Credential Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GitHostingRepoTreeRouter.cls
global with sharing class GitHostingRepoTreeRouter {
    
    @AuraEnabled(cacheable=true)
    global static GitRepoTreeResponseModel getFileTree(String stringifiedRepo, String path) {

        if (path == null) {
            path = '';
        }

        GitRepoTreeResponseModel responseModel;

        try {

            GitRepoModel repo = (GitRepoModel)JSON.deserialize(stringifiedRepo, GitRepoModel.class);

            Git_Hosting_Service__mdt config = GitHostingConfig.getSpecificGitHost(repo.hostingService);
            GitHostingService service = GitHostingConfig.getServiceInstance(repo.hostingService);

            String endpoint = GitHostingRepoTreeRouter.getFormattedRepoTreeEndpoint(config, repo.owner, repo.path, path, repo.mainBranch);

            HttpResponse res = CalloutManager.sendRequest(endpoint, 'GET', null, null);

            responseModel = res.getStatusCode() == 200 ?
                            service.parseGetFileTreeRequest(res) :
                            new GitRepoTreeResponseModel(service.handleError(res));

        } catch (Exception e) {

            System.debug(e.getStackTraceString());
            responseModel = new GitRepoTreeResponseModel(e.getMessage());
        }

        responseModel.tree.sort();

        return responseModel;
    }


    private static String getFormattedRepoTreeEndpoint(Git_Hosting_Service__mdt config, String ownerName, String repoSlug, String path, String branch) {

        return CalloutManager.getFormattedEndpoint(
            config.Named_Credential_Name__c, 
            String.format(config.Get_File_Tree_Endpoint__c, new String[]{ownerName, repoSlug, path, branch})
        );
    }
}